services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - user
      - product
      - order
      - payment
      - rabbitmq   # Add RabbitMQ as a dependency
    env_file:
      - ./api-gateway/.env

  user:
    build: ./user
    ports:
      - "8001:8001"
    env_file:
      - ./user/.env
    depends_on:
      - rabbitmq   # Add RabbitMQ as a dependency

  product:
    build: ./product
    ports:
      - "8002:8002"
    env_file:
      - ./product/.env
    depends_on:
      - rabbitmq   # Add RabbitMQ as a dependency

  order:
    build: ./order
    ports:
      - "8003:8003"
    env_file:
      - ./order/.env
    depends_on:
      - rabbitmq   # Add RabbitMQ as a dependency

  payment:
    build: ./payment
    ports:
      - "8004:8004"
    env_file:
      - ./payment/.env
    depends_on:
      - rabbitmq   # Add RabbitMQ as a dependency

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # For messaging
      - "15672:15672"  # RabbitMQ management console
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
